app: serverlessprojects

# Define stages in your workflow
stages:
  - name: dev
    autoDeploy: true  # Auto-deploy changes to dev
  - name: prod
    autoDeploy: false # Require manual approval for production

# Define services (if you have a monorepo with multiple services)
# In this case, we have a single service in the root directory
services:
  main:
    path: ./
    buildCommand: npm install && npm run layer:install
    # Add any pre/post-deploy hooks if needed
    # postDeploy: npm run post-deploy